### ISSUE TITLE
Add alpha adjustments

### ISSUE THREAD

**Issue by ericclack** [rodrigosetti/stamps#1]
Like this:

```
#lang s-exp stamps/lang

(define-shape row
  (circle
      [saturation 1   ]
      [hue        0   ]
      [brightness 0.5 ]
      [alpha      0.3 ])
  (row [translate   0.2 0.2 ]
       [scale       0.8     ])
)

(start-shape row)
```

**Comment by ericclack** [comment]
I'll have a look at the code and see if I can figure out how to do this. Feel free to suggest any pointers.

Cheers, 
-Eric.

**Comment by ericclack** [comment]
Here's the first find -- alpha is missing from the `provides` function in `main.rkt`:

```
diff --git a/main.rkt b/main.rkt
index e4d4cc7..9650f91 100644
--- a/main.rkt
+++ b/main.rkt
@@ -12,6 +12,7 @@
          hue
          saturation
          brightness
+         alpha
          maximum-render-cycles
          random-integer
          random-real
```

**Comment by ericclack** [comment]
Actually that's all there was to it, now this example works (note the negative alpha adjustments):

https://github.com/ericclack/racket-stamps/blob/alpha/examples/alpha.rkt

**Comment by rodrigosetti** [comment]
Thanks. Closing as per your contribution in #4
