### ISSUE TITLE
Why collect paths before rendering?

### ISSUE THREAD

**Issue by ericclack** [rodrigosetti/stamps#10]
Currently the app collects all paths in`render.rkt/record-paths` before rendering with `path-record.rkt/path-record%/replay`.

If I understand the intent correctly we do this so that we know the extent of the drawing (by looking at all shapes in it) before starting to draw anything, so that we get the right scale.

Rather than visiting all the shapes in the drawing first, could we make an educated guess and start drawing sooner? 

I think Context Free might do this -- well, you can see the drawing taking shape on the screen, whereas with Stamps the whole drawing is shown once it is finished.

What do you think? Worth exploring?

**Comment by rodrigosetti** [comment]
yes. definitely something worth exploring

**Comment by ericclack** [comment]
One more reason to collect paths before rending, to sort by z-order. 

So, I suggest we close this issue for now.
