### ISSUE TITLE
Can't reduce saturation with adjustments

### ISSUE THREAD

**Issue by ericclack** [rodrigosetti/stamps#11]
I would expect this to make a row of circles, with reduced saturation...

```
(define-shape row
  (circle
   [saturation 0.5]
   [hue        0  ]
   [brightness 0.5])
  (row [saturation -.3]
       [scale 0.8]
       [translate 1 0]))

(maximum-render-cycles 10)
(start-shape row)
```

However, all circles have the same saturation. 

I've compared a different version with the line ` (row [saturation .3]`, which works as expected with increasing saturation.

In the second version it seems that the function `combine-adjustment` gets param `adj` with more and more saturation, but in the first version `adj` continues to contain the identity color values of `0 0 0 1` -- maybe this is the problem?

I can't figure out how this first param to `combine-adjustment` gets updated ... perhaps it's in `make-shape-constructor` -- can you give me any info on this?

Cheers, 
-Eric.

**Comment by ericclack** [comment]
Interestingly if I change the identity value to: 

```
(define identity
    (adjustment (identity-matrix 3) 0 1 0 1))
```

I get the opposite problem, I can then only reduce saturation, not increase it.

**Comment by ericclack** [comment]
OK, I think I understand it now, and have got it working. We really need that tutorial to explain how to use adjustments! Examples to follow...

**Comment by ericclack** [comment]
Saturation ramping down:

```
(define-shape ramp-down
  (circle)
  (ramp-down [scale         0.8]
             [translate   1 0  ]
             [saturation   -0.3]))

(define-shape outer
  (ramp-down [saturation 1]
             [hue        0]
             [brightness 1]))

(maximum-render-cycles 10)
(start-shape outer)
```

**Comment by ericclack** [comment]
Saturation ramping up:

```
(define-shape ramp-up
  (circle)
  (ramp-up [saturation   0.3]
           [scale        0.8]
           [translate  1 0  ]))

(define-shape outer
  (ramp-up
   [hue        0]
   [brightness 1]))

(maximum-render-cycles 10)
(start-shape outer)
```

**Comment by ericclack** [comment]
So I suggest we close this issue.

**Comment by rodrigosetti** [comment]
nice discussion. thanks for documenting here 👍
