### ISSUE TITLE
Add z-order adjustments

### ISSUE THREAD

**Issue by ericclack** [rodrigosetti/stamps#15]
This example would really benefit from a z-order adjustment:
https://github.com/ericclack/racket-stamps-examples/blob/master/examples/eye1.rkt
...so that the pupil appears in front of the iris. 

I'm going to explore adding this adjustment, maybe by storing a dictionary of queues in path-record, keyed on z-index.

Let me know what you think...
-Eric.

**Comment by rodrigosetti** [comment]
nice. I guess a single dictionary would do - it has to be a data structure that we can insert and traverse in-order efficiently. a binary tree should work.

**Comment by ericclack** [comment]
Progress here using a binary heap, seems to work but more testing required:
https://github.com/ericclack/racket-stamps/tree/z-order

**Comment by ericclack** [comment]
OK, the ordering of paths with no z-order is wrong, as can be seen in examples/anemone.rkt

**Comment by ericclack** [comment]
Here's a question regarding the problems with priority queue implementations: https://stackoverflow.com/questions/47777070/priority-queue-in-racket
...I'm going to have a go adding a counter to the queue data.

**Comment by ericclack** [comment]
OK, I think this is working better, with items ordered by the sequence they were drawn in:
https://github.com/ericclack/racket-stamps/tree/z-order

I've created a new Priority Queue data structure here:
https://github.com/ericclack/racket-stamps/blob/z-order/private/priority-queue.rkt

Let me know what you think...
-Eric.

**Comment by ericclack** [comment]
See PR here: #17

**Comment by rodrigosetti** [comment]
👍
