### ISSUE TITLE
Add some examples from Context Free gallery

### ISSUE THREAD

**Issue by ericclack** [rodrigosetti/stamps#7]
I'm working through some of the examples here: 
https://contextfreeart.org/gallery2/index.html

I think it would be good to include some in the examples directory, or another directory. What do you think?

**Comment by ericclack** [comment]
Progress here:
https://github.com/ericclack/racket-stamps/tree/context-free-examples/examples

**Comment by ericclack** [comment]
I think this is ready to merge once you've reviewed my pull request on the master branch.

**Comment by rodrigosetti** [comment]
Thank you! reviewed and merged
