### ISSUE TITLE
Write documentation (scribble)

### ISSUE THREAD

**Issue by rodrigosetti** [rodrigosetti/stamps#9]

**Comment by ericclack** [comment]
I'd be happy to write a bit of documentation, do you have a suggestion of where to start?

**Comment by rodrigosetti** [comment]
cool. I don't have much of a plan, but maybe a tutorial + reference would be cool. I haven't used much scribble, but the syntax looks nice. I believe is possible to write a macro that will render stamps examples automatically.

**Comment by ericclack** [comment]
OK, before I learn scribble, here's my progress on some tutorials:
https://github.com/ericclack/racket-stamps/tree/tutorial/tutorial
...I'll add a bit more and then submit a pull request.

Cheers, 
-Eric.

**Comment by ericclack** [comment]
PR here #14

**Comment by rodrigosetti** [comment]
Closing as we have something started
